name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Trigger only on git tag like v1, v2, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t pramodkumar054/my-todo-app:${{ env.TAG }} .
          echo "Built image with tag pramodkumar054/my-todo-app:${{ env.TAG }}"

      - name: Push Docker image
        run: docker push pramodkumar054/my-todo-app:${{ env.TAG }}
